defaults: &defaults
  app:
    name: Zollaria-Dev
    auth_redirect_url: http://apps.facebook.com/zollaria-dev/home/
  facebook:
    app_id: "392700677463970"
    app_secret: "ea40f3de763aed759dd88e23947fbf55"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  app:
    name: Zollaria
    auth_redirect_url: http://apps.facebook.com/zollaria/home/
  facebook:
    app_id: "421010801275638"
    app_secret: "d1d761d4d3bd85b5d05e6e9a7f780776"

