defaults: &defaults
  app:
    name: Zollaria-Dev
    auth_redirect_url: http://apps.facebook.com/zollaria-dev/
    auth_redirect_url_in_app: /home
  facebook:
    app_id: "392700677463970"
    app_secret: "ea40f3de763aed759dd88e23947fbf55"
  amazon:
    associate_tag: "zollaria-20"
    access_key_id: "AKIAITELMYIODXH676PA"
    secret_access_key: "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"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  app:
    name: Zollaria
    auth_redirect_url: http://apps.facebook.com/zollaria/
    auth_redirect_url_in_app: /home
  facebook:
    app_id: "421010801275638"
    app_secret: "d1d761d4d3bd85b5d05e6e9a7f780776"
  amazon:
    associate_tag: "zollaria-20"
    access_key_id: "AKIAITELMYIODXH676PA"
    secret_access_key: "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"